version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'your_database_name'
      MYSQL_USER: 'your_mysql_user'
      MYSQL_PASSWORD: 'your_mysql_password'
      MYSQL_ROOT_PASSWORD: 'your_mysql_root_password'
    ports:
      - '3306:3306'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myproject  # 映射当前目录到容器的 /myproject 目录
    ports:
      - '8000:8000'
    depends_on:
      - db
